// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["postgres://7db51e8ea45fbcaabf37eb38db39e4e0fa9505e95932316749a53f16661e942e:sk_4yla4sRbQBpXuh_br_Pnk@db.prisma.io:5432/postgres?sslmode=require"],
  },
});
